[{"id":1053407556,"node_id":"R_kgDOPsm5RA","name":"Django-faille-CVE-2025-57833_test","full_name":"loic-houchi/Django-faille-CVE-2025-57833_test","private":false,"owner":{"login":"loic-houchi","id":194474185,"node_id":"U_kgDOC5dwyQ","avatar_url":"https://avatars.githubusercontent.com/u/194474185?v=4","url":"https://api.github.com/users/loic-houchi","html_url":"https://github.com/loic-houchi","type":"User","site_admin":false},"html_url":"https://github.com/loic-houchi/Django-faille-CVE-2025-57833_test","description":"","fork":false,"url":"https://api.github.com/repos/loic-houchi/Django-faille-CVE-2025-57833_test","created_at":"2025-09-09T12:08:05Z","updated_at":"2025-09-09T16:05:05Z","pushed_at":"2025-09-09T12:09:29Z","stargazers_count":1,"watchers_count":1,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":1,"default_branch":"main","score":1},{"id":1038466100,"node_id":"R_kgDOPeW8NA","name":"CVE-2025-24204","full_name":"FFRI/CVE-2025-24204","private":false,"owner":{"login":"FFRI","id":40906789,"node_id":"MDEyOk9yZ2FuaXphdGlvbjQwOTA2Nzg5","avatar_url":"https://avatars.githubusercontent.com/u/40906789?v=4","url":"https://api.github.com/users/FFRI","html_url":"https://github.com/FFRI","type":"Organization","site_admin":false},"html_url":"https://github.com/FFRI/CVE-2025-24204","description":"PoC and technical details of CVE-2025-24204","fork":false,"url":"https://api.github.com/repos/FFRI/CVE-2025-24204","created_at":"2025-08-15T08:48:37Z","updated_at":"2025-09-09T12:16:58Z","pushed_at":"2025-09-09T01:01:05Z","stargazers_count":48,"watchers_count":48,"forks_count":8,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":8,"watchers":48,"default_branch":"main","score":1}]